# Generated by Django 5.2.17 on 2026-08-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0002_batch_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.semester'),
        ),
    ]
