# Generated by Django 5.2.17 on 2026-09-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_batch_and_more'),
        ('students', '0003_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='class_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.classsection'),
        ),
    ]
