# Generated by Django 5.2.17 on 2026-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_marks_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
