# Generated by Django 5.2.17 on 2026-09-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseoffering_alter_enrollment_unique_together_and_more'),
        ('quizzes', '0004_quiz_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering'),
        ),
    ]
