# Generated by Django 5.2.17 on 2026-08-17 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_batch_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.semester')),
            ],
        ),
    ]
