# Generated by Django 5.2.17 on 2026-09-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_teacher'),
        ('courses', '0003_courseoffering_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='course',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering'),
        ),
    ]
