# Generated by Django 5.2.17 on 2026-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_submission_status_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='similarity_with',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
